# Generated by Django 4.0.3 on 2022-05-08 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_comments_newpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='newpost',
            name='post',
            field=models.CharField(max_length=64),
        ),
    ]
