# Generated by Django 4.0.3 on 2022-05-13 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_alter_comments_comment_alter_newpost_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewPost',
            new_name='Post',
        ),
    ]
