# Generated by Django 4.0.3 on 2022-05-15 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_profile_data'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='profile_data',
            new_name='Profile',
        ),
    ]
