# Generated by Django 4.0.3 on 2022-06-13 02:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_remove_profile_followers_profile_followers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='post_created_by_user',
        ),
        migrations.AlterField(
            model_name='profile',
            name='followers',
            field=models.ManyToManyField(default=None, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(default=None, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
    ]
