# Generated by Django 4.0.3 on 2022-06-20 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0015_connections_delete_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='connections',
            new_name='Connection',
        ),
    ]
