# Generated by Django 4.0.3 on 2022-07-03 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0017_connection_follower_id_post_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connection',
            name='follower_id_post',
        ),
        migrations.RemoveField(
            model_name='connection',
            name='following_id_post',
        ),
    ]
