# Generated by Django 4.0.3 on 2022-07-03 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0020_remove_connection_follower_id_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='follower_id_post',
            field=models.ManyToManyField(default=None, related_name='followerPost', to='network.post'),
        ),
        migrations.AddField(
            model_name='connection',
            name='following_id_post',
            field=models.ManyToManyField(default=None, to='network.post'),
        ),
    ]
